services:
  nginx:
    build: ./nginx
    container_name: lemoras-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lemoras-net

  ui:
    build: ./lemoras-ui
    container_name: lemoras-ui
    networks:
      - lemoras-net

  gateway:
    build: ./lemoras-gateway
    container_name: lemoras-gateway
    ports:
      - "80"  # internal
    depends_on:
      - core
      - modules
      - lemoras-db
    environment:
      PORT: 80
      MAIN_DOMAIN: dev.local
      SECURITY_TARGET_URL: http://lemoras-core
      SYSTEM_TARGET_URL: http://lemoras-core
      SERVICE_TARGET_URL: http://lemoras-modules
      FILE_TARGET_URL: http://file.dev.local
      SECRET_KEY: your-very-secure-random-secret
    networks:
      - lemoras-net

  core:
    build: ./lemoras-core
    container_name: lemoras-core
    expose:
      - "80"
    depends_on:
      - lemoras-db
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@lemoras-db:5432/zoe?sslmode=disable
      database_url: postgresql://postgres:mysecretpassword@lemoras-db:5432/zoe?sslmode=disable
      JWT_ISSUER: demo.com
      ROOT_ACCOUNT: demo@demo.com
      TOKEN_SECRET_KEY: demotokenkeysecret
      TOKEN_ROOT_SECRET_KEY: demotokenrootsecretkey
      TICKET_SECRET_KEY: demoticketsecretkey
      RATE_SECRET_KEY: demoratesecretkey
      X_API_KEY: XAPI-SecretKey
      COOKIE_ALLOWED_DOMAINS: dev.local,lemoras.com
      IS_HTTP_ONLY_AUTH_COOKIE: "true"
      IS_HTTP_SSL: "false"
    networks:
      - lemoras-net

  modules:
    build: ./lemoras-modules
    container_name: lemoras-modules
    expose:
      - "80"
    depends_on:
      - lemoras-db
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@lemoras-db:5432/zoe?sslmode=disable
      database_url: postgresql://postgres:mysecretpassword@lemoras-db:5432/zoe?sslmode=disable
      JWT_ISSUER: demo.com
      ROOT_ACCOUNT: demo@demo.com
      TOKEN_SECRET_KEY: demotokenkeysecret
      TOKEN_ROOT_SECRET_KEY: demotokenrootsecretkey
      TICKET_SECRET_KEY: demoticketsecretkey
      RATE_SECRET_KEY: demoratesecretkey
      X_API_KEY: XAPI-SecretKey
      COOKIE_ALLOWED_DOMAINS: dev.local,lemoras.com
      IS_HTTP_ONLY_AUTH_COOKIE: "true"
      IS_HTTP_SSL: "false"
    networks:
      - lemoras-net

  lemoras-db:
    image: postgres:15
    container_name: lemoras-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: zoe
    ports:
      - "5432:5432"
    networks:
      - lemoras-net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  lemoras-net:
    driver: bridge

volumes:
  pgdata:
